user:
  name_max_length: 50
  avatar_size: 5
  per_page: 10
  no_avatar: "default.jpg"
post:
  content_max_length: 500
  title_max_length: 100
  content_lorem_sentences: 20
  title_lorem_sentences: 3
  picture_size: 5
admin:
  date_format: "%d/%m/%Y"
